export const GET_TIME = {
  REQUEST: 'GET_TIME_REQUEST',
  SUCCESS: 'GET_TIME_SUCCESS',
  FAILURE: 'GET_TIME_FAILURE'
}

export const GET_PATHS = {
  REQUEST: 'GET_PATHS_REQUEST',
  SUCCESS: 'GET_PATHS_SUCCESS',
  FAILURE: 'GET_PATHS_FAILURE'
}
